FROM projectatomic/atomicapp:0.2.1

LABEL io.projectatomic.nulecule.specversion="0.0.2" \
      io.projectatomic.nulecule.providers="kubernetes,docker,openshift"

ADD /Nulecule LICENSE /application-entity/
ADD /artifacts /application-entity/artifacts
