apiVersion: v1
id: postgresql
spec:
  containers:
    - resources:
        limits:
          cpu: 100m
      name: postgresql
      image: docker.io/centos/postgresql-94-centos7
      env:
        - name: MYSQL_DATABASE
          value: $db_name
        - name: MYSQL_USER
          value: $db_user
        - name: MYSQL_PASSWORD
          value: $db_pass
      ports:
        - containerPort: 5432
metadata:
  name: postgresql
  labels:
    name: postgresql
kind: Pod
